### ISSUE TITLE
Crash when reading files created by Haskell xlsx library

### ISSUE THREAD

**Issue by stla** [nacnudus/tidyxl#13]
Hello,

This file causes a total crash a R when one tries to read it with `tidy_xlsx`:  [outfile.xlsx](https://www.dropbox.com/s/fovvio3wd3dwogc/outfile.xlsx?dl=0)

Possible cause: some XML tags are `variant` and `vector`, etc., instead of `vt:variant`, `vt:vector`.

I've checked that this is not due to the fact that the 0-th cellXf has not numFmt (like https://github.com/tidyverse/readxl/issues/225#issuecomment-272497601).

**Comment by stla** [comment]
Sorry this file is Excel-valid on my hard drive but it is not valid anymore after download from the above link...

**Comment by nacnudus** [comment]
What software created the file?

**Comment by nacnudus** [comment]
The file `xl/workbook.xml`, `<workbook><sheets><sheet>` uses attribute `ns:id` instead of `r:id`.

**Comment by stla** [comment]
This file was created by the Haskell library `xlsx`. 
`readxl` can read it without issue.

**Comment by nacnudus** [comment]
It doesn't work in the development version of readxl, because it uses the same attribute `r:id`.

```r
Error in read_xlsx_(path, sheet, col_names, col_types, na, nskip = skip,  : 
  `NA` not found
```

Fixing this in `tidyxl` requires also making sheet identification more robust generally, and removing the assumption that anything is defined in `xl/styles.xml`.

**Comment by stla** [comment]
It doesn't work with `openxlsx` as well.

```
> openxlsx::read.xlsx("C:/HaskellProjects/jsonxlsx/tests_XLSXfiles/outfile.xlsx", sheet=1)
Error in read.xlsx.default("C:/HaskellProjects/jsonxlsx/tests_XLSXfiles/outfile.xlsx",  : 
  Workbook has no worksheets
```

**Comment by qrilka** [comment]
@nacnudus why do you compare namespace prefixes and not namespace names?
Quoting https://www.w3.org/TR/2006/REC-xml-names11-20060816/ :

> Note that the prefix functions only as a placeholder for a namespace name. Applications should use the namespace name, not the prefix, in constructing names whose scope extends beyond the containing document.

**Comment by nacnudus** [comment]
@qrilka The rapidxml library doesn't allow namespace prefixes to be ignored.  There are a few forks that do, but my focus is currently on features rather than compatibility.

**Comment by nacnudus** [comment]
Sheet identification is more robust in f713f14.  But the file won't open unless I remove the need for styles to be present, possibly by defining a default 'normal' style.

**Comment by stla** [comment]
Hello @nacnudus 

@qrilka has fixed one prefix. Now `readxl` (development version) can read the file, but `tidyxl` still crashes the R session: [db0a04c.xlsx](https://www.dropbox.com/s/xp3hv6fq0bw6oqp/db0a04c.xlsx?dl=0).

But I have not tried the development version of `tidyxl`.

`openxlsx` still fails but generates a new error message:
```
> openxlsx::read.xlsx("db0a04c.xlsx")
Error in read.xlsx.default("db0a04c.xlsx") : expecting a single value
```

**Comment by stla** [comment]
Now I've tried the development version, it crashes as well.

**Comment by nacnudus** [comment]
Yes, it will still crash because the file doesn't define any styles.  Since styles and formatting are so central to the package, it will be a major change to ignore them.

**Comment by stla** [comment]
Ok.
Note that we can simply open the file in Excel and save it under a new name, and then `tidyxl` can read the new file (the file size doubles). But you probably know that. So unless the user doesn't have Excel this is not a severe issue. Maybe this also works with LibreOffice.
Otherwise, the user of the Haskell library can set some styles. We can assume it is his responsibility to do so if he wants a "standard" file that can be read by any xlsx reader.

**Comment by stla** [comment]
Hello @nacnudus 

I wanted to try to write a xlsx file with `Haskell xlsx` compatible with `tidyxl` and `openxlsx`. When you say the file doesn't have styles, do you mean the tags `cellStyleXfs` and `cellStyles` in `style.xml`? Are these tags enough? (also `cellXfs` but there's no problem regarding this tag, I think).

Actually I'm currently abandoning to use `Haskell xlsx` since I discovered `openxlsx` to write files and `tidyxl` to read files. When I didn't know these packages I was not able to write/read xlsx files having different types within the columns with R, that's why I used `Haskell xlsx`. But before abandoning I wanted to write an article on my blog to share my experience with `Haskell xlsx`, eventually.

**Comment by nacnudus** [comment]
92862ee falls back to a `styles.xml` defined in a blank worksheet created by Excel, and gives a warning.  It should allow the haskell file to be imported.  Please can you test it.

Your blog sounds interesting!  Have you seen that `readxl` has recently implemented list columns, for handling cells of different types within one column?

**Comment by stla** [comment]
> Have you seen that readxl has recently implemented list columns

Wow ! No, I didn't see that.

I'll try your update later (but you could also try it with the file I gave here: https://github.com/nacnudus/tidyxl/issues/13#issuecomment-280789708)

**Comment by stla** [comment]
> Have you seen that readxl has recently implemented list columns

But I want the comments too. The goal is to send the data to a web (shiny) app. I wrote a function based on `tidyxl`, returning JSON strings:

```
> sheetToJSON(sheet)
$data
{"Col1":[1,2],"Col2":["a","b"],"Col3":["2017-02-18","2017-02-19"]} 

$comments
{"Col1":[null,"a comment"],"Col2":["another comment",null],"Col3":[null,null]} 

$types
{"Col1":["numeric","numeric"],"Col2":["character","character"],"Col3":["date","date"]} 
```

**Comment by stla** [comment]
I've tried your update. Yes it works ! 
It's even possible to read the file prior to @qrilka's latest update (the change of the namespace prefix).

**Comment by nacnudus** [comment]
Thanks
