### ISSUE TITLE
option to get "data" only

### ISSUE THREAD

**Issue by stla** [nacnudus/tidyxl#16]
Hello,

 In general, I personally use only the field `data` of the output of `tidy_xlsx`.  It would be nice to have an option to read this field only, if it allows to gain speed.

**Comment by nacnudus** [comment]
There wouldn't be much speed gain for individual files.  Are you processing lots of files in a batch?

**Comment by stla** [comment]
No, but I've written a function which reads a file with `tidy_xlsx` and returns a dataframe with list columns (in order to preserve the cell types), and I observed that it is very slow when the file is big. I also made an executable with Haskell and I call it from R to generate the same output, and it is highly more efficient.
But maybe the slowness is not due to `tidy_xlsx` but to my code to get the dataframe (or maybe Haskell is awesome). I'll check and I'll tell you.

**Comment by stla** [comment]
I've checked. Indeed, the slowness is due to my own code, not to `tidy_xlsx`.

**Comment by nacnudus** [comment]
The github version of [readxl](https://github.com/tidyverse/readxl) now supports list columns to preserve cell types.  Might be better for you.

**Comment by stla** [comment]
Yes, you told me that in another thread. But with readxl, we have to know in advance the number of columns if we want to specify some classes.

**Comment by nacnudus** [comment]
Sorry, I forgot about that.
