### ISSUE TITLE
Add Named regions to returned data

### ISSUE THREAD

**Issue by sz-cgt** [nacnudus/tidyxl#17]
As you're already pulling the contents of the workbook.xml, how hard would it be to include the elements within <definedNames></definedNames> as well?

That would aid people looking at formulas and also those looking sub-sections of data withing  worksheets.

In a perfect world, readxl would do this, but @jennybc doesn't seem keen on the idea ([readxl #79](https://github.com/tidyverse/readxl/issues/79)).  At least a combination of this and readxl range selection would be an improvement.

**Comment by nacnudus** [comment]
Thanks for the suggestion.  I'm not opposed to this, thought it stretches the scope even further than #6 and perhaps belongs in the [rsheets](https://github.com/rsheets) packages.

The scope of this package is to import data.  If something isn't data, e.g. a graph, then it's out of scope.  Can you can think of an example where a named range contains data that isn't available in the cells?

Also are you aware that "named ranges" are in fact "named formulas", so they don't necessarily refer to a range?

**Comment by jennybc** [comment]
I'm really focused on getting a release of readxl out the door.

But I agree this should live somewhere! I have nothing more specific to say right now, other than I'd also like to see some meta-package evolve that helps access the contents of Excel and Google sheets at this level of detail.

I think the real hitch is learning which range of cells corresponds to the named range. Then there are various ways to get it; readxl is about to be capable of reading a range (https://github.com/tidyverse/readxl/pull/314). So this seems more about accessing workbook level metadata, like named ranges.

**Comment by sz-cgt** [comment]
I see the named ranges as a gateway to importing data.

My use case is the consumption of spreadsheets created by multiple actuaries where the workbooks contain similar data but the formats differ.  Getting them to change how the do their work is difficult; getting them to name the ranges of value is easier.

If I can pull the Named definitions, I can programmatically work around the rest.

**Comment by sz-cgt** [comment]
@jennyby, I agree this is really about workbook metadata (assuming your next release is “imminent”; I’m eagerly anticipating that release ☺).

Tidyxl already provides some of that metadata because it provides cell formatting information.  That’s why I’m suggesting to extend this package.

**Comment by sz-cgt** [comment]
close #17

@nacnudus looking at #6 lead me to the [openxlsx](https://github.com/awalker89/openxlsx) package which already extracts various workbook metadata.  It doesn't support xls but as my data is all in xlsx format I don't care.

**Comment by nacnudus** [comment]
I've been coding this up and I have a terrible feeling that Libreoffice interprets the `sheetId` attribute differently from Excel.

**Comment by nacnudus** [comment]
This is done (at least for Excel-generated files), but I'll leave this issue open until I've done written a vignette matching the names to the cells.

**Comment by nacnudus** [comment]
[Vignette](https://nacnudus.github.io/tidyxl/articles/data-validation-rules.html) complete.

**Comment by jennybc** [comment]
Congrats @nacnudus! I won't be tackling named ranges right away but hope to also expose in readxl for the next release. I might discuss with you when I'm really working on it. I, of course, have to make it feel uniform across xls and xlsx 😢.

**Comment by nacnudus** [comment]
Thanks @jennybc :blush:

We all have our problems -- you have xls, and I have to make a dplyr-friendly way of joining ranges to cell addresses!  I'd be delighted to discuss/collaborate.

The tough bit is detecting which names are ranges and which are just formulas.  In Enron, 10% of workbooks contain names that are neither ranges nor `#REF!` errors, but users probably know whether a name is a range or not when they specify it.

**Comment by nacnudus** [comment]
Oh man, I have to reopen this.  The `definedName` element is described in two different places in the ECMA standard, and I have, of course, only now discovered the one that mentions all the possible attributes, `18.2.5`, p. 1553.

If you want to see incomplete information, then you should look at `18.14.5`, p. 2020.

The additional attributes that seem relevant are `comment` and `hidden`.  The `comment` attribute can be set in the user interface (I forgot about that, duh), and the `hidden` attribute determines whether the user would know about the name via the user interface.

Names that are hidden by default seem to be print ranges and custom functions.  Examples from Enron:
* `wrn.RollDetail.`
* `_xlnm.Print_Area`
* `_Order1`

From the ECMA Part I:

> The following built-in names are defined in this SpreadsheetML specification:
> 
> * Print
>   * _xlnm .Print_Area: this defined name specifies the workbook's print area.
>   * _xlnm .Print_Titles: this defined name specifies the row(s) or column(s) to repeat at the top of each printed page.
> * Filter & Advanced Filter
>   * _xlnm .Criteria: this defined name refers to a range containing the criteria values to be used in applying an advanced filter to a range of data.
>   * _xlnm ._FilterDatabase: can be one of the following
>     1. this defined name refers to a range to which an advanced filter has been applied. This represents the source data range, unfiltered.
>     1. This defined name refers to a range to which an AutoFilter has been applied.
>   * _xlnm .Extract: this defined name refers to the range containing the filtered output values resulting from applying an advanced filter criteria to a source range.
> * Miscellaneous
>   * _xlnm .Consolidate_Area: the defined name refers to a consolidation area.
>   * _xlnm .Database: the range specified in the defined name is from a database data source.
>   * _xlnm .Sheet_Title: the defined name refers to a sheet title.
> 
> Built-in names reserved by SpreadsheetML begin with "_xlnm.". End users shall not use
> this string for custom names in the user interface.
