### ISSUE TITLE
Numeric columns rendering as dates

### ISSUE THREAD

**Issue by petersmp** [nacnudus/tidyxl#22]
While looking over the results from #5, I ran into a situation where some columns with numeric contents return as dates.

This is occurring with the file [example_formatting_complaint.xlsx](https://github.com/nacnudus/tidyxl/files/1345237/example_formatting_complaint.xlsx)

Reading in:

    test_full <- xlsx_cells("~/Downloads/example_formatting_complaint.xlsx")

Then, displaying the offending columns:

```
test_full %>%
  filter(col %in% c(2,3,6)) %>%
  arrange(col) %>%
  select(address, data_type, date, character)
```
returns:

```
# A tibble: 15 x 4
   address data_type       date character
     <chr>     <chr>     <dttm>     <chr>
 1      B1 character         NA     Count
 2      B2      date 1900-01-01      <NA>
 3      B3      date 1900-01-02      <NA>
 4      B4      date 1900-01-03      <NA>
 5      B5      date 1900-01-04      <NA>
 6      C1 character         NA     Value
 7      C2      date 1900-01-02      <NA>
 8      C3      date 1900-01-05      <NA>
 9      C4      date 1900-01-08      <NA>
10      C5      date 1900-01-11      <NA>
11      F1 character         NA ideal_run
12      F2      date 1900-01-01      <NA>
13      F3      date 1900-01-02      <NA>
14      F4      date 1900-01-03      <NA>
15      F5      date 1900-01-01      <NA>
```

The file contents are (with the columns `Count`, `Value`, and `ideal_run` matching the data shown above):

|ID             | Count| Value|Note                                             |ideal_product | ideal_run|ideal_category |ideal_result |ideal_altCat      |
|:--------------|-----:|-----:|:------------------------------------------------|:-------------|---------:|:--------------|:------------|:-----------------|
|A-1-TEST       |     1|     2|Test was great                                   |A             |         1|TEST           |OK           |TEST              |
|A-2-PRODUCTION |     2|     5|Released product                                 |A             |         2|PRODUCTION     |OK           |PRODUCTION        |
|A-3-~PRODUCTION~ |     3|     8|Flaw found after packaging; retained for testing |A             |         3|PRODUCTION     |FAIL         |failed_PRODUCTION |
|B-1-TEST       |     4|    11|Test failed                                      |B             |         1|TEST           |OK           |PRODUCTION        |

I am running:

- Linux Ubuntu 16.04.3 LTS (xenial)
- R version 3.4.1 (2017-06-30) (Single Candle)
- tidyxl version tidyxl_0.2.3.9000 (reinstalled from development version today, confirmed it is current)
- dplyr version dplyr_0.7.1 (only used for the filtering/output above; the date issue is present even without dplyr loaded)

**Comment by nacnudus** [comment]
Thanks for the reprex.  Unfortunately I still can't reproduce it.

Could you try installing from 963b1cf335247ef7057ce3c6bf978203fe7d270d, which is the commit before I upgraded the date detection of custom formats?  Alternatively, could you run `devtools::test()` on the package and see what happens?

**Comment by nacnudus** [comment]
I've just managed to reproduce it in a docker container, so will be able to investigate now.

```
devtools::session_info()
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2017-10-20                  

Packages ----------------------------------------------------------------------
 package    * version    date       source                    
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.2)            
 base       * 3.4.2      2017-09-29 local                     
 bindr        0.1        2016-11-13 CRAN (R 3.4.2)            
 bindrcpp   * 0.2        2017-06-17 CRAN (R 3.4.2)            
 compiler     3.4.2      2017-09-29 local                     
 datasets   * 3.4.2      2017-09-29 local                     
 devtools     1.13.3     2017-08-02 CRAN (R 3.4.2)            
 digest       0.6.12     2017-01-27 CRAN (R 3.4.2)            
 dplyr      * 0.7.4      2017-09-28 CRAN (R 3.4.2)            
 glue         1.1.1      2017-06-21 CRAN (R 3.4.2)            
 graphics   * 3.4.2      2017-09-29 local                     
 grDevices  * 3.4.2      2017-09-29 local                     
 magrittr     1.5        2014-11-22 CRAN (R 3.1.2)            
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.2)            
 methods    * 3.4.2      2017-09-29 local                     
 pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.2)            
 R6           2.2.2      2017-06-17 CRAN (R 3.4.2)            
 Rcpp         0.12.13    2017-09-28 CRAN (R 3.4.2)            
 rlang        0.1.2      2017-08-09 CRAN (R 3.4.2)            
 stats      * 3.4.2      2017-09-29 local                     
 tibble       1.3.4      2017-08-22 CRAN (R 3.4.2)            
 tidyxl     * 0.2.3.9000 2017-10-20 local (nacnudus/tidyxl@NA)
 tools        3.4.2      2017-09-29 local                     
 utils      * 3.4.2      2017-09-29 local                     
 withr        2.0.0      2017-07-28 CRAN (R 3.4.2)      
```
