### ISSUE TITLE
Custom number format misinterpreted as date?

### ISSUE THREAD

**Issue by nacnudus** [nacnudus/tidyxl#24]
`#,##0_M_M_M;#,##0_M_M_M;_(@_M_M_M` is being interpreted as date.  Excel doesn't render the numbers as dates.

Sheet "Table 11" of [2015.xlsx](https://github.com/nacnudus/tidyxl/files/1908128/2015.xlsx).

```r
tidyxl::is_date_format("#,##0_M_M_M;#,##0_M_M_M;_(@_M_M_M")
# [1] TRUE
```

**Comment by da11an** [comment]
Similar: I have a custom number format (0.0############E-0) that is being interpreted as a date. It is not. While custom number formats are often used for dates, I don't think this should be assumed.
