### ISSUE TITLE
Separate a column into new columns based on the number of leading spaces

### ISSUE THREAD

**Issue by zx8754** [nacnudus/tidyxl#41]
Feature request, relevant StackOverflow post:
 - https://stackoverflow.com/q/51757816/680068

**Comment by nacnudus** [comment]
Thanks.  I like this idea and I'm thinking about it, but currently short of time.  Happy to review a PR.

**Comment by nacnudus** [comment]
Moving this to [unpivotr](https://github.com/nacnudus/unpivotr/issues/17).
