### ISSUE TITLE
missing cell

### ISSUE THREAD

**Issue by millerjef** [nacnudus/tidyxl#43]
I am importing an irregularly structured xlsx file. 

tidyxl::xlsx_cells runs without errors; however, one column has the wrong number of values. D25 is missing. Other values of column D are present and other values of row 25 are also present.

This is one of many data "forms." The other xlsx spreadsheets import correctly without any apparent problems.

Cell D25 in the problematic excel file appears to be formatted differently from the rest of the cells. Using Excel, I can "solve" the problem by copying the formatting from an adjacent good cell (i.e., D26), saving a new file, and importing. Similarly, I can copy the formatting of the bad cell (e.g., D25) and paste the formatting to a previously good cell (e.g., D24) resulting in the previously good cell (D24) now also missing (D24 and D25)!

Unfortunately, I can't easily share this file without dumping a lot of the sensitive data.

Given these observations, I attempted to recreate a MRE, to verify that formatting differences might be causing issues. I was unsuccessful recreating the problem. I tried the following:

```r
library(openxlsx)
library(tidyxl)

## Create analagous sample dataframe

df <- head(mtcars)
df[, 4] <- c(110,110,"","","","")

## add df to "control" and "expiremental" workbooks using openxlsx

wb <- createWorkbook()
addWorksheet(wb, "mtcars")
addWorksheet(wb, "mtcars_dropped_cell")
writeData(wb, 1, df, colNames = TRUE)
writeData(wb, 2, df, colNames = TRUE)

## mimic style of worksheet

base_style <- createStyle(
  fontName = "Arial", 
  fontSize = 10, 
  fontColour = NULL,
  numFmt = "GENERAL", 
  border = NULL,
  borderColour = getOption("openxlsx.borderColour", "black"),
  borderStyle = getOption("openxlsx.borderStyle", "thin"), 
  bgFill = NULL,
  fgFill = NULL, 
  halign = "center", 
  valign = "bottom", 
  textDecoration = "bold",
  wrapText = TRUE, 
  textRotation = NULL, 
  indent = NULL
)

## apply baseline style to control and experimental worksheets

addStyle(
  wb, 1, style = base_style, 
  rows = 1:7,
  cols = 1:7,
  gridExpand = TRUE
)

addStyle(
  wb, 2, style = base_style, 
  rows = 1:7,
  cols = 1:7,
  gridExpand = TRUE
)

## mimic style of missing cell as closely as possible and apply only to cell 
## in experimental worksheet

try_style <- createStyle(
  fontName = "Calibri", 
  fontSize = 11, 
  fontColour = NULL,
  numFmt = "GENERAL", 
  border = NULL,
  borderColour = getOption("openxlsx.borderColour", "black"),
  borderStyle = getOption("openxlsx.borderStyle", "thin"), 
  bgFill = NULL,
  fgFill = NULL, 
  halign = NULL, 
  valign = , 
  textDecoration = NULL,
  wrapText = FALSE, 
  textRotation = NULL, 
  indent = NULL
)

## apply style to D5 in experimental worksheet

addStyle(
  wb,
  2,
  style = try_style,
  rows = 5,
  cols = 4
)

saveWorkbook(wb, "./mtcars_test.xlsx", overwrite = TRUE)

## import using tidyxl

tidy_base_wb <- xlsx_cells(
  path = "./mtcars_test.xlsx",
  sheets = 1, 
  check_filetype = TRUE
)

tidy_prob_wb <- xlsx_cells(
  path = "./mtcars_test.xlsx",
  sheets = 2, 
  check_filetype = TRUE
)
```

I'm open to suggestions on how to further troubleshoot this.

**Comment by nacnudus** [comment]
Hi @millerjef, thanks for reporting this.

Which column of the data frame is missing the values?  E.g. if cell D24 has a value in the `character` column, is D25 `NA` in the `character` column?  Maybe the value of D25 is in one of the other columns, e.g. `numeric`, `date`, `logical` or `error`.

If that isn't the problem then I really need a file to work with, so here are a couple of suggestions to create one:

1. Create a new workbook, and paste cells D24 and D25 into it.  If that doesn't reproduce the problem, then try option 2 below.
1. Delete all the cells except D24 and D25, and send me the file.  Step by step this would mean
    a. Delete columns A:D (select the whole column, right-click, delete).  The original column D would now be column A.
    b. Then select columns B to the edge of the sheet, and delete those.
    c. Repeat for the rows.
    d. Finally, delete any other sheets in the workbook.

**Comment by nacnudus** [comment]
@millerjef do you still have this problem?  I'll close the issue now, but feel free to reopen it if it isn't solved.
