### ISSUE TITLE
xlsx_validation() using ranges on different sheets

### ISSUE THREAD

**Issue by davidski** [nacnudus/tidyxl#46]
`xlsx_validation()` doesn't seem to pick up data validation rules when the list of allowed values is on a different sheet. This ([test_validation.xlsx](https://github.com/nacnudus/tidyxl/files/2654318/test_validation.xlsx)) test file generates zero detected data validation rules, even though one is present.

Tested syntax

``` r
tidyxl::xlsx_validation(here::here("data/test_validation.xlsx"))
```

and

``` r
tidyxl::xlsx_validation(here::here("data/test_validation.xlsx"), sheets = c(1, 2))
```

**Comment by davidski** [comment]
The test file was generated with Excel for Mac (Office 365 - V16.16.4). I have an internal file using a similar style of validation rule created with Excel for Windows (Office 365) that generates the same problem. 😦 

Thanks for the quick response and the handy package!

**Comment by davidski** [comment]
Sure thing! Here's a basic one.

[test_validation_w_formula.xlsx](https://github.com/nacnudus/tidyxl/files/2655258/test_validation_w_formula.xlsx)

**Comment by nacnudus** [comment]
Similar bug to https://github.com/PHPOffice/PhpSpreadsheet/issues/388.  Need to handle `x14` and `xm` extensions to the spec.

**Comment by nacnudus** [comment]
@davidski Please try `devtools::install_github(nacnudus/tidyxl)`, and reopen this issue if it doesn't work.  Thanks for the helpful report and files.

I'm curious what you use the `xlsx_validation()` for in case I could support the workflow better somehow.  It's a pretty niche function.

**Comment by davidski** [comment]
Thanks! An install off of `master` seems to be working!

The use case on this is a bit odd - I have some Excel workbooks that are used for structured data entry (uploading) into a commercial closed source tool. The workbooks have some validation applied to ensure the data is put into the correct format, but the rules themselves are not well documented. I am looking to use `tidyxl` to pull out the validation rules and reverse engineer them, allowing these uploads to be created with other tools (like Shiny, for instance).

Appreciate the fix on this!

**Comment by nacnudus** [comment]
That sounds niche enough! Thanks for the explanation, I hope it works out.
