### ISSUE TITLE
E and e exponent symbols are wrongly interpreted as dates

### ISSUE THREAD

**Issue by nacnudus** [nacnudus/tidyxl#52]
E.g. `0E1`.

Reported by @da11an (thanks!) in https://github.com/nacnudus/tidyxl/issues/24#issuecomment-503712465 and https://github.com/nacnudus/tidyxl/issues/51

**Comment by nacnudus** [comment]
Some tests here https://github.com/andersnm/ExcelNumberFormat/blob/ba055b3ee7fa87abfeb2e26f7f46fbb09e22ea0c/test/ExcelNumberFormat.Tests/Class1.cs

**Comment by da11an** [comment]
Hi @nacnudus, is format detection part of this repo or a dependency? What file or dependency? I'd love to help.

**Comment by nacnudus** [comment]
Hi, sorry for still not having fixed this. The bug is in here: https://github.com/nacnudus/tidyxl/blob/2650076323315f7c21fc392ca3f007591c65d47e/src/date.h#L79

See also readxl https://github.com/tidyverse/readxl/issues/388

**Comment by da11an** [comment]
I tried defining a date format in excel as `0.0e+0` but it wasn't allowed, but `0.0E+0` was. So I don't think there's a conflict here with lowercase e usage for era/year. Uppercase for scientific notation, lowercase for era. I'll submit a pull request.
