### ISSUE TITLE
Reading csv files

### ISSUE THREAD

**Issue by skiamu** [nacnudus/tidyxl#54]
Is there any change to use tidyxl for reading csv files?
I tried convert the file using rio::convert and than xlsx_cells but the conversion fails since the csv file is untidy.

![image](https://user-images.githubusercontent.com/16693811/66699418-fe06c300-ece6-11e9-9338-82803818ff81.png)

**Comment by nacnudus** [comment]
For a csv file try [melt_csv()](https://readr.tidyverse.org/reference/melt_delim.html) in the readr package.

**Comment by skiamu** [comment]
Great, thank you very much!
