### ISSUE TITLE
Data Validation

### ISSUE THREAD

**Issue by maschere** [nacnudus/tidyxl#6]
Hi nacnudus,

first of thank you very much for your work on this package. It bridges a gap in my workflow and so far it works very good and quite fast.

I would like to suggest to add one feature: **extracting data validation rules from Excel cells**

Best
Max

**Comment by nacnudus** [comment]
Hi maschere, Glad to hear it's useful. I have a major update nearly ready, which I'll push to a dev branch soon.

Interesting suggestion. Can I ask what your use case is?

**Comment by maschere** [comment]
Thanks for your qick reply. Looking forward to checking out that update now.

My use case is the following: We collect lots of microeconomic data using Excel surveys. There are many data quality checks and recalculations in those Excel files. Sometimes the participants accidently overwrite calculated cells with their own estimates or fill in invalid data into validation cells. We protect the sheets, but that does not always work due to copy & paste.
 Hence, I need to check, wether a formula has been changed / deleted (and write back the original formula, for which I fall back to XLConnect / POI currently) and also wether a data validation is overwritten / invalid.

So for my use case, two crucial features are a) getting all the formulas from the workbook (I saw that propagating shared formulas is luckily already on your roadmap) and b) getting all the validation info from cells (only fixed drop-down lists in my case)

**Comment by nacnudus** [comment]
That's a good use-case, though to be honest it stretches the scope that I have in mind for this package, which focuses on data.  Formulas are a bit of a grey area.  The delay is that I haven't yet learned how to tokenize them.  But conditional formatting, data validation, filters, pivot tables, while they're all cell-related aren't really data, they're gadgets.  I'd consider a pull-request though.

The https://github.com/rsheets project has a much wider scope, and since Jenny Bryan has joined RStudio, development might start again.

A possible workaround: extend https://github.com/hrbrmstr/xlsxtractr to extract the data validations (it's all R code, no C++), https://github.com/rsheets/cellranger to convert the `sqref` into row/column ranges, and then join them back onto the tidyxl data.

I'll leave this open in case there is more interest / offers of help.

Note to self: ECMA Part 1 page 1619.

**Comment by nacnudus** [comment]
@maschere This is (finally!) [available](https://nacnudus.github.io/tidyxl/reference/xlsx_validation.html) as of 69bfb1082167fc7d899f28e56170ea0394ac7655.  Please can you try it and and let me know what you think?

> `xlsx_validation()` returns the data validation rules applied to cells in xlsx (Excel) files. Data validation rules control what constants can be entered into a cell, e.g. any whole number between 0 and 9, or one of several values from another part of the spreadsheet.

> Each data validation rule can only apply to cells on one worksheet, so `xlsx_validation()` returns a named list of data frames, one for each worksheet, describing the rules on that worksheet.

```
examples <- system.file("extdata/examples.xlsx", package = "tidyxl")
xlsx_validation(examples)
#> $Sheet1
#> # A tibble: 15 x 13
#>               ref       type           operator            formula1
#>             <chr>      <chr>              <chr>               <chr>
#>  1           A106      whole            between                   0
#>  2           A107    decimal         notBetween                   0
#>  3           A108       list               <NA>              $B$108
#>  4           A109       list               <NA>              $B$108
#>  5           A110       date            between 2017-01-01 00:00:00
#>  6           A111       time            between            00:00:00
#>  7           A112 textLength            between                   0
#>  8           A113     custom               <NA>     A113<=LEN(B113)
#>  9           A114      whole         notBetween                   0
#> 10 A115,A121:A122      whole              equal                   0
#> 11           A116      whole           notEqual                   0
#> 12           A117      whole        greaterThan                   0
#> 13           A118      whole           lessThan                   0
#> 14           A119      whole greaterThanOrEqual                   0
#> 15           A120      whole    lessThanOrEqual                   0
#> # ... with 9 more variables: formula2 <chr>, allow_blank <lgl>,
#> #   show_input_message <lgl>, prompt_title <chr>, prompt_body <chr>,
#> #   show_error_message <lgl>, error_title <chr>, error_body <chr>,
#> #   error_symbol <chr>
```
