### ISSUE TITLE
Change licence to MIT

### ISSUE THREAD

**Issue by nacnudus** [nacnudus/tidyxl#63]
Tidyxl was licenced under GPL-3 for compatibility with certain fragments of code, cribbed from readxl, that were written at RStudio by Hadley Wickham and Jenny Bryan.  That code has recently be re-licensed under MIT, so with their approval I would like to re-license tidyxl too.

@hadley and @jennybc , would you permit me to re-license tidyxl with the MIT license? If so, please comment "I agree" below.

**Comment by hadley** [comment]
I agree!

**Comment by jennybc** [comment]
I agree

**Comment by nacnudus** [comment]
Thank you both https://github.com/nacnudus/tidyxl/commit/65b8d7ea7afb2532480203feaa1908e7c8f7c8e0
