### ISSUE TITLE
How to import data from a URL?

### ISSUE THREAD

**Issue by marine-ecologist** [nacnudus/tidyxl#76]
Not an issue as much as a question, but: Is it possible with tidyxl to import xlsx files from a URL as with read.csv? For example:

cells <- xlsx_cells("https://www.seanoe.org/data/00400/51167/data/51949.xlsx")

**Comment by nacnudus** [comment]
Unfortunately not.  An xlsx file is in fact a zipped directory of files.  Tidyxl uses R's `utils::unzip()` to extract what it needs, and `unzip()` doesn't support URLs.  RStudio has recently created an alternative `unzip()` https://github.com/r-lib/zip but it too only supports local files.  The readr package [also can't read zip files from URLs](https://community.rstudio.com/t/using-readrs-read-tsv-to-read-a-zip-compressed-tsv-file-from-a-url/26332/2), and [nor can readxl](https://github.com/tidyverse/readxl/issues/278), although they are thinking about how to do it.  It's clearly possible to do, just fiddly.  I'd welcome a PR.
